<?php

/**
 * PluginCoreReleaseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginCoreReleaseTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginCoreReleaseTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginCoreRelease');
    }
}