<?php

/**
 * CoreRelease
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    www.sympalphp.org
 * @subpackage model
 * @author     Ryan Weaver <ryan.weaver@iostudio.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class CoreRelease extends PluginCoreRelease
{
}
