all:
  sympal_config:
    installed: true
    sfSympalBlogPlugin:
      installed: true
    sfSympalCommentsPlugin:
      installed: true
      default_status: Approved
      enabled: true
      enable_recaptcha: true
      requires_auth: false
    sfSympalTagsPlugin:
      installed: false
    current_version: 1.0.0-ALPHA3
    i18n: true
    upgrade_version_history:
      - 0.7.0__1
      - 0.7.0__2
      - 1.0.0_ALPHA4__1
      - 1.0.0_ALPHA4__2
      - 1.0.0_ALPHA4__3
      - 1.0.0_ALPHA4__4
    language_codes:
      - en
    theme:
      default_theme: sympal
