<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version1 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('core_release', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'title' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'details' => 
             array(
              'type' => 'clob',
              'length' => '',
             ),
             'version' => 
             array(
              'type' => 'string',
              'length' => '50',
             ),
             'archive_filename' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'content_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('core_release');
    }
}